spring.application.name=app_mysql
# 1. Connexion à votre MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/flutter_backend
spring.datasource.username=root
# REMPLACEZ LE MOT DE PASSE CI-DESSOUS PAR LE VÔTRE (laissez vide si vous n'en avez pas)
spring.datasource.password=Soprano23@
# 2. Demander à Spring de créer les tables automatiquement
spring.jpa.hibernate.ddl-auto=update
# 3. (Optionnel) Pour voir le SQL généré dans la console
spring.jpa.show-sql=true